# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170321_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ar_name',
            field=models.TextField(max_length=100, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0628\u0627\u0644\u0639\u0631\u0628\u064a'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='en_name',
            field=models.TextField(max_length=100, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0628\u0627\u0644\u0625\u0646\u062c\u0644\u064a\u0632\u064a'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=14, verbose_name='\u0631\u0642\u0645 \u0627\u0644\u062c\u0648\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(unique=True, verbose_name='\u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u062c\u0627\u0645\u0639\u064a'),
        ),
    ]
