# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_colleges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college_year',
            field=models.CharField(choices=[('', '--'), ('1', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u0623\u0648\u0644\u0649'), ('2', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062b\u0627\u0646\u064a\u0629'), ('3', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062b\u0627\u0644\u062b\u0629'), ('4', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u0631\u0627\u0628\u0639\u0629'), ('5', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062e\u0627\u0645\u0633\u0629'), ('6', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u0633\u0627\u062f\u0633\u0629'), ('7', '\u0633\u0646\u0629 \u0627\u0644\u0627\u0645\u062a\u064a\u0627\u0632')], default='', max_length=1, verbose_name='\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u0629'),
        ),
    ]
