# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 15:23
from __future__ import unicode_literals

from django.db import migrations

def add_colleges(apps, schema_editor):
    College = apps.get_model('accounts', 'College')
    College.objects.create(city="R", name="M", gender="M")
    College.objects.create(city="R", name="P", gender="M")
    College.objects.create(city="R", name="D", gender="M")
    College.objects.create(city="R", name="B", gender="M")
    College.objects.create(city="R", name="A", gender="M")
    College.objects.create(city="R", name="I", gender="M")
    College.objects.create(city="R", name="M", gender="F")
    College.objects.create(city="R", name="P", gender="F")
    College.objects.create(city="R", name="D", gender="F")
    College.objects.create(city="R", name="B", gender="F")
    College.objects.create(city="R", name="A", gender="F")
    College.objects.create(city="R", name="I", gender="F")
    College.objects.create(city="R", name="N", gender="F")
    College.objects.create(city="J", name="M", gender="M")
    College.objects.create(city="J", name="B", gender="M")
    College.objects.create(city="J", name="A", gender="M")
    College.objects.create(city="J", name="N", gender="F")
    College.objects.create(city="J", name="M", gender="F")
    College.objects.create(city="J", name="B", gender="F")
    College.objects.create(city="J", name="A", gender="F")
    College.objects.create(city="A", name="N", gender="F")
    College.objects.create(city="A", name="A", gender="F")
    College.objects.create(city="A", name="A", gender="M")

def remove_colleges(apps, schema_editor):
    College = apps.get_model('accounts', 'College')
    College.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170324_0941'),
    ]

    operations = [
       migrations.RunPython(
            add_colleges,
            reverse_code=remove_colleges),
    ]
