# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_colleges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ar_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='ar_first_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u0648\u0644'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ar_last_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u062e\u064a\u0631'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ar_middle_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u0648\u0633\u0637'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='en_first_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u0648\u0644'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='en_last_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u062e\u064a\u0631'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='en_middle_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0623\u0648\u0633\u0637'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(choices=[('', '--'), ('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629'),
        ),
        migrations.AlterField(
            model_name='college',
            name='gender',
            field=models.CharField(choices=[('', '--'), ('F', '\u0637\u0627\u0644\u0628\u0627\u062a'), ('M', '\u0637\u0644\u0627\u0628')], max_length=1, verbose_name='\u0627\u0644\u062c\u0646\u0633'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(choices=[('', '--'), ('M', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0637\u0628'), ('A', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0639\u0644\u0648\u0645 \u0627\u0644\u0637\u0628\u064a\u0629 \u0627\u0644\u062a\u0637\u0628\u064a\u0642\u064a\u0629'), ('P', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0635\u064a\u062f\u0644\u0629'), ('D', '\u0643\u0644\u064a\u0629 \u0637\u0628 \u0627\u0644\u0623\u0633\u0646\u0627\u0646'), ('B', '\u0643\u0644\u064a\u0629 \u0627\u0644\u0639\u0644\u0648\u0645 \u0648 \u0627\u0644\u0645\u0647\u0646 \u0627\u0644\u0635\u062d\u064a\u0629'), ('N', '\u0643\u0644\u064a\u0629 \u0627\u0644\u062a\u0645\u0631\u064a\u0636'), ('I', ' \u0643\u0644\u064a\u0629 \u0627\u0644\u0635\u062d\u0629 \u0627\u0644\u0639\u0627\u0645\u0629 \u0648\u0627\u0644\u0645\u0639\u0644\u0648\u0645\u0627\u062a\u064a\u0629 \u0627\u0644\u0635\u062d\u064a\u0629')], max_length=1, verbose_name='\u0627\u0644\u0627\u0633\u0645'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('', '--'), ('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', '--'), ('F', '\u0637\u0627\u0644\u0628\u0627\u062a'), ('M', '\u0637\u0644\u0627\u0628')], max_length=1, verbose_name='\u0627\u0644\u062c\u0646\u0633'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0645\u0633\u062a\u062e\u062f\u0645\u0640/\u0640\u0629'),
        ),
    ]
