# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_colleges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='gender',
            field=models.CharField(choices=[('F', '\u0637\u0627\u0644\u0628\u0627\u062a'), ('M', '\u0637\u0644\u0627\u0628')], max_length=1, verbose_name='\u0627\u0644\u062c\u0646\u0633'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', '\u0637\u0627\u0644\u0628\u0627\u062a'), ('M', '\u0637\u0644\u0627\u0628')], max_length=1, verbose_name='\u0627\u0644\u062c\u0646\u0633'),
        ),
    ]
