# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170326_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='\u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u062c\u0627\u0645\u0639\u064a'),
        ),
    ]
