# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170326_0947'),
        ('accounts', '0006_auto_20170326_2041'),
    ]

    operations = [
    ]
