# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.FileField(upload_to=b'', verbose_name='\u0627\u0644\u062e\u0637\u0629')),
                ('cv', models.FileField(upload_to=b'', verbose_name='\u0627\u0644\u0633\u064a\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629')),
                ('certificates', models.FileField(null=True, upload_to=b'', verbose_name='\u0627\u0644\u0634\u0647\u0627\u062f\u0627\u062a \u0648\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0627\u062a')),
                ('gpa', models.FloatField(null=True, verbose_name='\u0627\u0644\u0645\u0639\u062f\u0644 \u0627\u0644\u062c\u0627\u0645\u0639\u064a')),
                ('is_rejected', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
            ],
            options={
                'verbose_name': '\u0627\u0644\u0645\u0631\u0634\u062d\u0640/\u0640\u0629',
                'verbose_name_plural': '\u0627\u0644\u0645\u0631\u0634\u062d\u0648\u0646/\u0627\u0644\u0645\u0631\u0634\u0651\u062d\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='NominationAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.FileField(upload_to=b'', verbose_name='\u0627\u0644\u062e\u0637\u0629')),
                ('cv', models.FileField(upload_to=b'', verbose_name='\u0627\u0644\u0633\u064a\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629')),
            ],
            options={
                'verbose_name': '\u0627\u0644\u0645\u0631\u0634\u062d\u0640/\u0640\u0629 \u0627\u0644\u0645\u0624\u0647\u0644\u0640/\u0640\u0629',
                'verbose_name_plural': '\u0627\u0644\u0645\u0631\u0634\u062d\u0648\u0646/\u0627\u0644\u0645\u0631\u0634\u0651\u062d\u0627\u062a \u0627\u0644\u0645\u0624\u0647\u0644\u0648\u0646/\u0627\u0644\u0645\u0624\u0647\u0644\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u0635\u0628')),
                ('entity', models.CharField(choices=[('club', '\u0646\u0627\u062f\u064a \u0627\u0644\u0637\u0644\u0627\u0628'), ('council', '\u0627\u0644\u0645\u062c\u0644\u0633 \u0627\u0644\u0637\u0644\u0627\u0628\u064a \u0627\u0644\u0627\u0633\u062a\u0634\u0627\u0631\u064a')], default='club', max_length=50, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u0635\u0628')),
                ('city', models.CharField(blank=True, choices=[('', '\u0639\u0627\u0645\u0629'), ('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], default='', max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629')),
                ('note', models.TextField(blank=True, verbose_name='\u0645\u0644\u0627\u062d\u0638\u0629')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
                ('colleges_allowed_to_nominate', models.ManyToManyField(related_name='nominate', to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629 \u0628\u0627\u0644\u062a\u0631\u0634\u064a\u062d')),
                ('colleges_allowed_to_vote', models.ManyToManyField(related_name='vote', to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629 \u0628\u0627\u0644\u062a\u0635\u0648\u064a\u062a')),
            ],
            options={
                'verbose_name': '\u0627\u0644\u0645\u0646\u0635\u0628',
                'verbose_name_plural': '\u0627\u0644\u0645\u0646\u0627\u0635\u0628',
            },
        ),
        migrations.CreateModel(
            name='Referendum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='\u0627\u0644\u0633\u0646\u0629')),
                ('title', models.CharField(max_length=100, verbose_name='\u0627\u0644\u0645\u0648\u0636\u0648\u0639')),
                ('description', models.TextField(verbose_name='\u0627\u0644\u0648\u0635\u0641')),
                ('opening_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0628\u062a\u062f\u0627\u0621')),
                ('closing_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0646\u062a\u0647\u0627\u0621')),
                ('colleges_allowed', models.ManyToManyField(to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629')),
            ],
        ),
        migrations.CreateModel(
            name='ReferendumFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ImageField(upload_to=b'', verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629')),
                ('referendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Referendum', verbose_name='\u0627\u0644\u0627\u0633\u062a\u0641\u062a\u0627\u0621')),
            ],
        ),
        migrations.CreateModel(
            name='SACYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0628\u062f\u0627\u064a\u0629')),
                ('end_date', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0646\u0647\u0627\u064a\u0629')),
                ('election_nomination_start_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062a\u0631\u0634\u064a\u062d\u0627\u062a')),
                ('election_nomination_end_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0646\u0647\u0627\u064a\u0629 \u0627\u0644\u062a\u0631\u0634\u064a\u062d\u0627\u062a')),
                ('election_nomination_announcement_datetime', models.DateTimeField(null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0625\u0639\u0644\u0627\u0646 \u0627\u0644\u062a\u0631\u0634\u064a\u062d\u0627\u062a')),
                ('election_vote_start_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062a\u0635\u0648\u064a\u062a')),
                ('election_vote_end_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0646\u0647\u0627\u064a\u0629 \u0627\u0644\u062a\u0635\u0648\u064a\u062a')),
            ],
            options={
                'verbose_name': '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u0623\u0643\u0627\u062f\u064a\u0645\u064a\u0629',
                'verbose_name_plural': '\u0627\u0644\u0633\u0646\u0648\u0627\u062a \u0627\u0644\u0623\u0643\u0627\u062f\u064a\u0645\u064a\u0629',
            },
        ),
        migrations.CreateModel(
            name='VoteNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
                ('nomination_announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.NominationAnnouncement', verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='\u0627\u0644\u0645\u0646\u0635\u0628')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0635\u0648\u0651\u0650\u062a')),
            ],
            options={
                'verbose_name': '\u0635\u0648\u062a',
                'verbose_name_plural': '\u0627\u0644\u0623\u0635\u0648\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='VoteReferendum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
                ('referendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Referendum', verbose_name='\u0627\u0644\u0627\u0633\u062a\u0641\u062a\u0627\u0621')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0635\u0648\u0651\u0650\u062a')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.SACYear', verbose_name='\u0627\u0644\u0633\u0646\u0629'),
        ),
        migrations.AddField(
            model_name='nominationannouncement',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='\u0627\u0644\u0645\u0646\u0635\u0628'),
        ),
        migrations.AddField(
            model_name='nominationannouncement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='\u0627\u0644\u0645\u0646\u0635\u0628'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
    ]
