# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20170324_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.FileField(upload_to=b'', verbose_name='\u0627\u0644\u062e\u0637\u0629')),
                ('cv', models.FileField(upload_to=b'', verbose_name='\u0627\u0644\u0633\u064a\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u0635\u0628')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
                ('colleges_allowed_to_nominate', models.ManyToManyField(related_name='nominate', to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629 \u0628\u0627\u0644\u062a\u0631\u0634\u064a\u062d')),
                ('colleges_allowed_to_vote', models.ManyToManyField(related_name='vote', to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629 \u0628\u0627\u0644\u062a\u0635\u0648\u064a\u062a')),
            ],
        ),
        migrations.CreateModel(
            name='Referendum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='\u0627\u0644\u0633\u0646\u0629')),
                ('title', models.CharField(max_length=100, verbose_name='\u0627\u0644\u0645\u0648\u0636\u0648\u0639')),
                ('description', models.TextField(verbose_name='\u0627\u0644\u0648\u0635\u0641')),
                ('opening_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0628\u062a\u062f\u0627\u0621')),
                ('closing_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0646\u062a\u0647\u0627\u0621')),
                ('colleges_allowed', models.ManyToManyField(to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629')),
            ],
        ),
        migrations.CreateModel(
            name='ReferendumFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Referendum', verbose_name='\u0627\u0644\u0627\u0633\u062a\u0641\u062a\u0627\u0621')),
            ],
        ),
        migrations.CreateModel(
            name='SACYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0628\u062f\u0627\u064a\u0629')),
                ('end_date', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0646\u0647\u0627\u064a\u0629')),
                ('election_nomination_start_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062a\u0631\u0634\u064a\u062d\u0627\u062a')),
                ('election_nomination_end_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0646\u0647\u0627\u064a\u0629 \u0627\u0644\u062a\u0631\u0634\u064a\u062d\u0627\u062a')),
                ('election_vote_start_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062a\u0635\u0648\u064a\u062a')),
                ('election_vote_end_datetime', models.DateTimeField(verbose_name='\u062a\u0627\u0631\u064a\u062e \u0646\u0647\u0627\u064a\u0629 \u0627\u0644\u062a\u0635\u0648\u064a\u062a')),
            ],
        ),
        migrations.CreateModel(
            name='VoteNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
                ('nomination', models.ForeignKey(on_delete='id', to='voting.Nomination', to_field='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='\u0627\u0644\u0645\u0635\u0648\u0651\u0650\u062a')),
            ],
        ),
        migrations.CreateModel(
            name='VoteReferendum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0642\u062f\u064a\u0645')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
                ('referendum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Referendum', verbose_name='\u0627\u0644\u0627\u0633\u062a\u0641\u062a\u0627\u0621')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='\u0627\u0644\u0645\u0635\u0648\u0651\u0650\u062a')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='year',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='voting.SACYear', verbose_name='\u0627\u0644\u0633\u0646\u0629'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='\u0627\u0644\u0645\u0646\u0635\u0628'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='\u0627\u0644\u0645\u0631\u0634\u062d'),
        ),
    ]
