# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenomination',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Nomination', verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
    ]
