# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_add_year_2016_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationannouncement',
            name='cv',
            field=models.FileField(default='', upload_to=b'', verbose_name='\u0627\u0644\u0633\u064a\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='nominationannouncement',
            name='plan',
            field=models.FileField(default='', upload_to=b'', verbose_name='\u0627\u0644\u062e\u0637\u0629'),
        ),
        migrations.AlterField(
            model_name='nominationannouncement',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
        migrations.AlterField(
            model_name='position',
            name='colleges_allowed_to_nominate',
            field=models.ManyToManyField(related_name='nomination_positions', to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629 \u0628\u0627\u0644\u062a\u0631\u0634\u064a\u062d'),
        ),
        migrations.AlterField(
            model_name='position',
            name='colleges_allowed_to_vote',
            field=models.ManyToManyField(related_name='voting_positions', to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0627\u062a \u0627\u0644\u0645\u0633\u0645\u0648\u062d\u0629 \u0628\u0627\u0644\u062a\u0635\u0648\u064a\u062a'),
        ),
        migrations.AlterField(
            model_name='sacyear',
            name='election_vote_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0646\u0647\u0627\u064a\u0629 \u0627\u0644\u062a\u0635\u0648\u064a\u062a'),
        ),
        migrations.AlterField(
            model_name='sacyear',
            name='election_vote_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062a\u0635\u0648\u064a\u062a'),
        ),
    ]
