# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_add_year_2016_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name': '\u0627\u0644\u0645\u0631\u0634\u062d\u0640/\u0640\u0629', 'verbose_name_plural': '\u0627\u0644\u0645\u0631\u0634\u062d\u0648\u0646/\u0627\u0644\u0645\u0631\u0634\u0651\u062d\u0627\u062a'},
        ),
        migrations.AddField(
            model_name='nomination',
            name='certificates',
            field=models.FileField(null=True, upload_to=b'', verbose_name='\u0627\u0644\u0634\u0647\u0627\u062f\u0627\u062a \u0648\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0627\u062a'),
        ),
    ]
