# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_add_year_2016_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='entity',
            field=models.CharField(choices=[('club', '\u0646\u0627\u062f\u064a \u0627\u0644\u0637\u0644\u0627\u0628'), ('council', '\u0627\u0644\u0645\u062c\u0644\u0633 \u0627\u0644\u0637\u0644\u0627\u0628\u064a \u0627\u0644\u0627\u0633\u062a\u0634\u0627\u0631\u064a')], default='club', max_length=50, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u0635\u0628'),
        ),
        migrations.AddField(
            model_name='referendumfigure',
            name='figure',
            field=models.ImageField(default='', upload_to=b'', verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
        migrations.AlterField(
            model_name='position',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.SACYear', verbose_name='\u0627\u0644\u0633\u0646\u0629'),
        ),
        migrations.AlterField(
            model_name='votenomination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0635\u0648\u0651\u0650\u062a'),
        ),
        migrations.AlterField(
            model_name='votereferendum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0635\u0648\u0651\u0650\u062a'),
        ),
    ]
