# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20170329_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='photo',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u0634\u062e\u0635\u064a\u0629'),
        ),
    ]
