# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20170326_1132'),
        ('voting', '0003_auto_20170326_0947'),
    ]

    operations = [
    ]
