# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0003_field_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnelectedWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='\u0627\u0644\u0645\u0646\u0635\u0628')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='votenomination',
            name='is_counted',
            field=models.BooleanField(default=True),
        ),
    ]
