# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20170526_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unelectedwinner',
            options={'verbose_name': '\u0641\u0627\u0626\u0632 \u062a\u0644\u0642\u0627\u0626\u064a', 'verbose_name_plural': '\u0641\u0627\u0626\u0632\u0648\u0646 \u062a\u0644\u0642\u0627\u0626\u064a\u0648\u0646'},
        ),
    ]
