# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20170526_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unelectedwinner',
            options={'verbose_name': '\u0641\u0627\u0626\u0632/\u0629 \u062a\u0644\u0642\u0627\u0626\u064a\u064b\u0627', 'verbose_name_plural': '\u0627\u0644\u0641\u0627\u0626\u0632\u0648\u0646/\u0627\u0644\u0641\u0627\u0626\u0632\u0627\u062a \u062a\u0644\u0642\u0627\u0626\u064a\u064b\u0627'},
        ),
    ]
