# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20170329_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='certificates',
            field=models.FileField(null=True, upload_to=b'', verbose_name='\u0627\u0644\u0634\u0647\u0627\u062f\u0627\u062a \u0648\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0627\u062a'),
        ),
    ]
