# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_nomination_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='gpa',
            field=models.FloatField(null=True, verbose_name='\u0627\u0644\u0645\u0639\u062f\u0644 \u0627\u0644\u062c\u0627\u0645\u0639\u064a'),
        ),
    ]
