# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_nomination_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='gpa',
            field=models.CharField(default='\u063a\u064a\u0631 \u0645\u0632\u0648\u0651\u062f', max_length=4, verbose_name='\u0627\u0644\u0645\u0639\u062f\u0644 \u0627\u0644\u062c\u0627\u0645\u0639\u064a'),
        ),
    ]
