# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0007_nomination_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.FileField(null=True, upload_to=b'', verbose_name='\u0627\u0644\u062e\u0637\u0629')),
                ('cv', models.FileField(null=True, upload_to=b'', verbose_name='\u0627\u0644\u0633\u064a\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629')),
                ('certificates', models.FileField(null=True, upload_to=b'', verbose_name='\u0627\u0644\u0634\u0647\u0627\u062f\u0627\u062a \u0648\u0627\u0644\u0645\u0633\u0627\u0647\u0645\u0627\u062a')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='\u0627\u0644\u0645\u0646\u0635\u0628')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d')),
            ],
            options={
                'verbose_name': '\u0627\u0644\u0645\u0631\u0634\u062d\u0640/\u0640\u0629 \u0627\u0644\u0645\u0624\u0647\u0644\u0640/\u0640\u0629',
                'verbose_name_plural': '\u0627\u0644\u0645\u0631\u0634\u062d\u0648\u0646/\u0627\u0644\u0645\u0631\u0634\u0651\u062d\u0627\u062a \u0627\u0644\u0645\u0624\u0647\u0644\u0648\u0646/\u0627\u0644\u0645\u0624\u0647\u0644\u0627\u062a',
            },
        ),
    ]
