# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_Add_NominationAnnouncement_Model'),
        ('voting', '0008_add_nomination_announcement_date_field'),
    ]

    operations = [
    ]
