# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_add_GPA_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='gpa',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0639\u062f\u0644 \u0627\u0644\u062c\u0627\u0645\u0639\u064a'),
        ),
    ]
