# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_merge_20170427_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationannouncement',
            name='cv',
            field=models.FileField(default='empty', upload_to=b'', verbose_name='\u0627\u0644\u0633\u064a\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nominationannouncement',
            name='plan',
            field=models.FileField(default='empty', upload_to=b'', verbose_name='\u0627\u0644\u062e\u0637\u0629'),
            preserve_default=False,
        ),
    ]
