# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_add_NomintaionAnnouncement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationannouncement',
            name='certificates',
        ),
        migrations.AlterField(
            model_name='nominationannouncement',
            name='cv',
            field=models.FileField(default='', upload_to=b'', verbose_name='\u0627\u0644\u0633\u064a\u0631\u0629 \u0627\u0644\u0630\u0627\u062a\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='nominationannouncement',
            name='plan',
            field=models.FileField(default='', upload_to=b'', verbose_name='\u0627\u0644\u062e\u0637\u0629'),
        ),
        migrations.AlterField(
            model_name='nominationannouncement',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
    ]
