# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_removed_null_true_filedfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationannouncement',
            name='certificates',
        ),
    ]
