# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_NULLable_GPA_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='gpa',
        ),
    ]
