# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20170429_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votenomination',
            name='nomination',
        ),
        migrations.AddField(
            model_name='votenomination',
            name='nomination_announcement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.NominationAnnouncement', verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
    ]
