# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20170503_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votenomination',
            options={'verbose_name': '\u0635\u0648\u062a', 'verbose_name_plural': '\u0627\u0644\u0623\u0635\u0648\u0627\u062a'},
        ),
    ]
