# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_auto_20170503_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=55, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u0635\u0628'),
        ),
    ]
