# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_increase_position_max_length'),
        ('voting', '0012_position_city'),
    ]

    operations = [
    ]
