# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_merge_20170507_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='votenomination',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.Position', verbose_name='\u0627\u0644\u0645\u0646\u0635\u0628'),
        ),
        migrations.AlterField(
            model_name='nominationannouncement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
        migrations.AlterField(
            model_name='position',
            name='city',
            field=models.CharField(blank=True, choices=[('', '\u0639\u0627\u0645\u0629'), ('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], default='', max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629'),
        ),
    ]
