# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20170507_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='note',
            field=models.TextField(blank=True, verbose_name='\u0645\u0644\u0627\u062d\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='votenomination',
            name='nomination_announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.NominationAnnouncement', verbose_name='\u0627\u0644\u0645\u0631\u0634\u0651\u064e\u062d'),
        ),
    ]
