# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_colleges'),
        ('voting', '0004_winner_annoucement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('', '--'), ('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('title', models.CharField(max_length=100, verbose_name='\u0627\u0644\u0639\u0646\u0648\u0627\u0646')),
                ('description', models.TextField(verbose_name='\u0627\u0644\u0648\u0635\u0641')),
                ('picture', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0635\u0648\u0631\u0629')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0631\u0641\u0639')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u0645\u0642\u0631\u0648\u0621\u0629\u061f')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0629')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.SACYear', verbose_name='\u0627\u0644\u0633\u0646\u0629')),
            ],
            options={
                'verbose_name': '\u0627\u0644\u0645\u0642\u062a\u0631\u064e\u062d/\u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0629',
                'verbose_name_plural': '\u0627\u0644\u0645\u0642\u062a\u0631\u062d\u0627\u062a/\u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u0627\u0644\u0639\u0646\u0648\u0627\u0646')),
                ('body', models.TextField(verbose_name='\u0627\u0644\u0639\u0631\u0636')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0646\u0634\u0631')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0639\u062f\u064a\u0644')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.SACYear', verbose_name='\u0627\u0644\u0633\u0646\u0629')),
            ],
        ),
    ]
