# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_add_feedback_and_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'verbose_name': '\u0627\u0644\u062e\u0628\u0631', 'verbose_name_plural': '\u0627\u0644\u0623\u062e\u0628\u0627\u0631'},
        ),
    ]
