# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_colleges'),
        ('voting', '0004_winner_annoucement'),
        ('general', '0002_small_edits'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('', '--'), ('R', '\u0627\u0644\u0631\u064a\u0627\u0636'), ('J', '\u062c\u062f\u0629'), ('A', '\u0627\u0644\u0623\u062d\u0633\u0627\u0621')], max_length=1, verbose_name='\u0627\u0644\u0645\u062f\u064a\u0646\u0629')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('question', models.TextField(verbose_name='\u0627\u0644\u0633\u0624\u0627\u0644')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0631\u0641\u0639')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u0645\u0642\u0631\u0648\u0621\u0629\u061f')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College', verbose_name='\u0627\u0644\u0643\u0644\u064a\u0629')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.SACYear', verbose_name='\u0627\u0644\u0633\u0646\u0629')),
            ],
            options={
                'verbose_name': '\u0633\u0624\u0627\u0644 \u0627\u0644\u0645\u0646\u0627\u0638\u0631\u0629',
                'verbose_name_plural': '\u0623\u0633\u0626\u0644\u0629 \u0627\u0644\u0645\u0646\u0627\u0638\u0631\u0629',
            },
        ),
    ]
