# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_add_debate_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debateq',
            name='city',
        ),
        migrations.RemoveField(
            model_name='debateq',
            name='college',
        ),
        migrations.RemoveField(
            model_name='debateq',
            name='email',
        ),
    ]
