# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_debateQ_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student_id',
            field=models.CharField(blank=True, max_length=9, verbose_name='\u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u062c\u0627\u0645\u0639\u064a'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u0627\u0644\u0627\u0633\u0645'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('', '--'), ('AC', '\u0623\u0643\u0627\u062f\u064a\u0645\u064a\u0629'), ('SC', '\u0646\u0627\u062f\u064a \u0627\u0644\u0637\u0644\u0627\u0628'), ('SA', '\u0634\u0624\u0648\u0646 \u0627\u0644\u0637\u0644\u0627\u0628'), ('RR', '\u0627\u0644\u0623\u0646\u0638\u0645\u0629 \u0648\u0627\u0644\u0642\u0648\u0627\u0646\u064a\u0646')], default='', max_length=2, verbose_name='\u062a\u0635\u0646\u064a\u0641 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.SACYear', verbose_name='\u0627\u0644\u0633\u0646\u0629'),
        ),
    ]
